CREATE OR REPLACE VIEW CUSTOMERS_VIEW AS
	SELECT customer_phoneNumber AS PHONE, customer_name AS NAME, given AS PAID, remain AS BAKI, dealDate AS SHOPINGDATE, reason AS HISTORY
	FROM  CUSTOMERS NATURAL JOIN Deals;

CREATE OR REPLACE VIEW TCASH_VIEW AS
	SELECT dealDate AS SHOPINGDATE, totalCash AS TOTALCASH, customer_phoneNumber AS PHONE
	FROM  TCash;

CREATE OR REPLACE VIEW TREMAIN_VIEW AS
	SELECT RemainDate AS SHOPINGDATE, totalRemain AS TOTALREMAIN, customer_phoneNumber AS PHONE
	FROM  TRemains;

CREATE OR REPLACE VIEW TOTALDEAL_VIEW AS
	SELECT RemainDate AS SHOPINGDATE, totalCash AS TOTALCASH, totalRemain AS TOTALREMAIN, customer_phoneNumber AS PHONE
	FROM  TCash NATURAL JOIN TRemains;

commit;