SET VERIFY OFF;
SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER customerIn
BEFORE INSERT
ON Customers
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Inserting in Customers table.');
END;
/

CREATE OR REPLACE TRIGGER customerDUp
BEFORE UPDATE
ON Customers
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Updateing  Customers table.');
END;
/

CREATE OR REPLACE TRIGGER dealIn
BEFORE INSERT
ON Deals
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Instering in Deals table.');
END;
/

CREATE OR REPLACE TRIGGER dealUp
BEFORE UPDATE
ON Deals
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Updating Deals table.');
END;
/

CREATE OR REPLACE TRIGGER cashIn
BEFORE INSERT
ON TCash
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Inserting in Cash table.');
END;
/

CREATE OR REPLACE TRIGGER cashUp
BEFORE UPDATE
ON TCash
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Updating Cash table.');
END;
/

CREATE OR REPLACE TRIGGER remainIn
BEFORE INSERT
ON TRemains
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Inserting in Remains table.');
END;
/

CREATE OR REPLACE TRIGGER remainUp
BEFORE UPDATE
ON TRemains
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Updating Remains table.');
END;
/

commit;